apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-frontend-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-frontend-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 3
          periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-backend-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-backend-deployment
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 150
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 3
          periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-worker-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-worker-deployment
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
    - type: Pods
      pods:
        metric:
          name: queue_depth
        target:
          type: AverageValue
          averageValue: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 5
          periodSeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-ai-service-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-ai-service-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Pods
      pods:
        metric:
          name: ai_requests_per_second
        target:
          type: AverageValue
          averageValue: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 10
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-redis-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-redis-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 10
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-mongodb-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-mongodb-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: mongodb_operations_per_second
        target:
          type: AverageValue
          averageValue: 1000
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
        - type: Percent
          value: 10
          periodSeconds: 180
        - type: Pods
          value: 1
          periodSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 50
          periodSeconds: 180
        - type: Pods
          value: 1
          periodSeconds: 180

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-elasticsearch-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-elasticsearch-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: elasticsearch_queries_per_second
        target:
          type: AverageValue
          averageValue: 500
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1200
      policies:
        - type: Percent
          value: 10
          periodSeconds: 240
        - type: Pods
          value: 1
          periodSeconds: 240
    scaleUp:
      stabilizationWindowSeconds: 240
      policies:
        - type: Percent
          value: 50
          periodSeconds: 240
        - type: Pods
          value: 1
          periodSeconds: 240

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-rabbitmq-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-rabbitmq-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: rabbitmq_messages_per_second
        target:
          type: AverageValue
          averageValue: 1000
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 10
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-prometheus-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-prometheus-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800
      policies:
        - type: Percent
          value: 10
          periodSeconds: 360
        - type: Pods
          value: 1
          periodSeconds: 360
    scaleUp:
      stabilizationWindowSeconds: 360
      policies:
        - type: Percent
          value: 50
          periodSeconds: 360
        - type: Pods
          value: 1
          periodSeconds: 360

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harmony-grafana-hpa
  namespace: harmony
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harmony-grafana-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800
      policies:
        - type: Percent
          value: 10
          periodSeconds: 360
        - type: Pods
          value: 1
          periodSeconds: 360
    scaleUp:
      stabilizationWindowSeconds: 360
      policies:
        - type: Percent
          value: 50
          periodSeconds: 360
        - type: Pods
          value: 1
          periodSeconds: 360